"""add system prompt to conversation

Revision ID: a33fb01b138a
Revises: ed3850a26aae
Create Date: 2026-02-23 13:36:12.984558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33fb01b138a'
down_revision: Union[str, Sequence[str], None] = 'ed3850a26aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add as nullable first
    op.add_column(
        "conversation",
        sa.Column("system_prompt", sa.Text(), nullable=True),
    )
    op.add_column(
        "conversation",
        sa.Column("prompt_version", sa.BigInteger(), nullable=True),
    )

    # Backfill existing rows
    op.execute(
        "UPDATE conversation SET system_prompt = 'You are Molly, a helpful assistant.' WHERE system_prompt IS NULL"
    )
    op.execute(
        "UPDATE conversation SET prompt_version = 1 WHERE prompt_version IS NULL"
    )

    # Enforce NOT NULL
    op.alter_column("conversation", "system_prompt", nullable=False)
    op.alter_column("conversation", "prompt_version", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'prompt_version')
    op.drop_column('conversation', 'system_prompt')
    # ### end Alembic commands ###
