"""add summary to conversation

Revision ID: cdf1bae1a121
Revises: a33fb01b138a
Create Date: 2026-02-23 14:11:19.489596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf1bae1a121'
down_revision: Union[str, Sequence[str], None] = 'a33fb01b138a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversation', sa.Column('summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'summary_updated_at')
    op.drop_column('conversation', 'summary')
    # ### end Alembic commands ###
