"""add memory tables

Revision ID: f0af7e340fb1
Revises: cdf1bae1a121
Create Date: 2026-02-24 15:30:14.223107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0af7e340fb1'
down_revision: Union[str, Sequence[str], None] = 'cdf1bae1a121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('memory_item_id', sa.BigInteger(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['memory_item_id'], ['memory_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_embedding')
    op.drop_table('memory_item')
    # ### end Alembic commands ###
